- name: Provision a testapp
  hosts: all
  become: yes
  become_user: root
  #remote_user: "{{ server_user }}"
  vars:
    update_apt_cache: yes
  vars_files:
    - vars/vars.yml

  roles:
    #- base
    - web
    - nginx
